lazarv/react-server

packages/react-server/lib/build/static.mjs
packages/react-server/lib/handlers/static.mjs

Fixes static exporting of routes specified in the root configuration file. Correct URL instance is now used in the rendering context.
Static export now also renders with the `Accept` header set to `text/x-component`, and so exporting will work not just on initial loading of pages, but also on client-side navigation to the exported routes.
Static file handler now works for both HTML and RSC exports.
Fixes minor issue with filename formatting in the reporting of the static export.

fix: static export

---

packages/react-server/lib/plugins/react-server.mjs
packages/react-server/server/entry.server.jsx

Fixes HMR when rendering without any client components. When no client components used to render the HTML response the renderer will include the entry module for HMR, but it will not start hydration on the client.
In a production build when no client components were used rendering will not include any script tags and so there will be no hydration on the client.

fix: dev hmr

---

examples/chakra-ui/app/Chakra.jsx
examples/chakra-ui/app/Providers.jsx
examples/chakra-ui/app/layout.jsx
examples/chakra-ui/app/page.jsx
examples/chakra-ui/package.json
examples/chakra-ui/react-server.config.mjs
packages/react-server/lib/build/client.mjs
packages/react-server/lib/build/server.mjs
packages/react-server/lib/dev/create-logger.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/plugins/asset.mjs
packages/react-server/lib/plugins/optimize-deps.mjs
packages/react-server/lib/plugins/root-module.mjs
pnpm-lock.yaml

With this PR the framework in development mode relies on Vite's dependency optimizer in a cleaner and simpler way to handle CommonJS dependencies.
Adds a new Chakra UI example to have another third-party library usage as a test case for module resolution.
Cleans up some inline Vite / Rollup plugin code.
Another possible enhancement to fix issues around third-party libraries, related to issues:
- Mantine / use client not respected https://github.com/lazarv/react-server/issues/20
- MUI 6.x / React__namespace.createContext is not a function https://github.com/lazarv/react-server/issues/22

fix: vite deps optimizer usage

---

examples/remote/index.jsx
examples/remote/package.json
examples/remote/react-server.config.mjs
packages/react-server/lib/dev/action.mjs
packages/react-server/lib/start/action.mjs

Fixes using IPv6 listener hostname in dev / production servers.
Updates the `RemoteComponent` example to use an IPv6 remote for one of the MFE apps.
Fixes https://github.com/lazarv/react-server/issues/28

fix: using ipv6 listener hostname

---

packages/react-server-router/plugin.mjs

Ensure output directory exists before trying to write generated `react-server-router.d.ts` router type definition file.
Fixes https://github.com/lazarv/react-server/issues/32

fix: ensure output directory exists before router type generation

---

packages/react-server-router/plugin.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/start/manifest.mjs

Fixes stylesheet ordering when collecting imported stylesheets in dev mode / production mode / file-system based router. Stylesheets imported by a parent module should be loaded first to maintain CSS specificity.

fix: stylesheet ordering

---

packages/react-server/lib/loader/module-alias.mjs

Fixes `react-is` alias module resolution to make it optional when package is not part of the production build.

fix: react-is alias resolution

---

examples/photos/src/app/(root).layout.tsx
examples/photos/src/app/@modal/photos/[id].page.tsx
examples/photos/src/app/page.tsx
examples/photos/src/components/frame/Frame.tsx
examples/photos/tsconfig.json
examples/photos/vite.config.mjs
packages/react-server/lib/build/client.mjs
packages/react-server/lib/build/server.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/utils/config.mjs

Support an object as `resolve.alias` configuration in Vite / react-server configuration files.
Use path aliases in Photos example to use `resolve.alias` as an object.

fix: applying resolve.alias config

---

examples/mantine/react-server.config.mjs
examples/mantine/src/components/AppLayout.tsx
examples/mantine/src/components/AppLogo.tsx
examples/mantine/src/components/MyDates.tsx
examples/todo/react-server.config.json
packages/react-server/lib/build/server.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/handlers/error.mjs
packages/react-server/lib/plugins/optimize-deps.mjs
packages/react-server/lib/utils/module.mjs

This PR makes some changes to have a better developer experience around module resolution and the Vite deps optimizer.
- removes need in case of some packages to define a workaround `resolve.alias` entry for it
- removes need to define a package as external for some packages
- fixes Vite deps optimizer caching
- use `holdUntilCrawlEnd` by default in Vite deps optimizer
- invalidate all modules in case of a server-side error to be able to reload modules on refresh

feat: optimize deps enhancements

---

docs/src/pages/en/(pages)/framework/micro-frontends.mdx
package.json

Fix link in docs at https://react-server.dev/framework/micro-frontends to https://react-server.dev/router/client-navigation
Updates pnpm to latest

fix: docs outlets link

---

docs/src/components/EditPage.jsx
docs/src/mdx-components.jsx
docs/src/pages.mjs
docs/src/pages/(root).layout.jsx
docs/src/pages/@breadcrumb/[[lang]]/[category]/(breadcrumb).[...slug].page.jsx
docs/src/pages/@header/[[lang]]/(header).[[...slug]].page.jsx
docs/src/pages/en/(pages)/integrations/mantine.mdx
docs/src/pages/en/(pages)/integrations/mui.mdx
docs/src/pages/en/(pages)/integrations/react-query.mdx
docs/src/pages/en/(pages)/integrations/tailwind-css.mdx
docs/src/pages/en/(pages)/integrations/typescript.mdx
docs/src/pages/en/(pages)/integrations/vite.mdx
docs/src/pages/en/integrations.(index).mdx
docs/src/pages/global.css

Adds "Integrations" section to docs, including:
- Vite
- TypeScript
- Tailwind CSS
Placeholder pages for:
- TanStack Query
- Mantine UI
- Material UI
Adds "Edit this page" link to start editing the page on GitHub

feat(docs): integrations

---

docs/src/pages/en/(pages)/framework/micro-frontends.mdx
examples/remote/index.jsx
packages/react-server/package.json
packages/react-server/server/remote.d.ts
packages/react-server/server/remote.jsx
packages/react-server/server/router.d.ts
packages/react-server/server/router.jsx

This PR moves the `RemoteComponent` into it's own module at `@lazarv/react-server/remote` to resolve an eager client component import issue around `ReactServerComponent` and `@lazarv/react-server/navigation` forcing all apps to use the navigation client components. Long-term solution will be to not build client component entries which were not used by the application even when the client component was imported in any way and to make tree-shaking work for client component references.

fix: move RemoteComponent to @lazarv/react-server/remote module

---

docs/src/pages/(root).layout.jsx
docs/src/pages/en/(pages)/framework/cli.mdx
packages/react-server/bin/commands/dev.mjs
packages/react-server/config/index.mjs
packages/react-server/lib/dev/action.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/plugins/file-router/plugin.mjs
packages/react-server/lib/plugins/use-server.mjs

Adds a `watch` option to development mode, defaults to `true`.
When enabled, configuration file changes restarts the development server to apply any changes made in the configuration.

feat: development mode watch config file changes

---

test/__test__/apps/mantine.spec.mjs
test/utils.mjs
test/vitest.config.build.mjs
test/vitestSetup.mjs

Fixes "examples" test suite by removing timeout waits and using change-based waits.
Fixes disabling adapters while running tests.
Fixes build and start `NODE_ENV` set to production.
Adds retry logic to the Mantine test case to reload the page when a server-side error occurs, providing a workaround for now for an async dependency optimization issue.

fix: examples test suite

---

packages/react-server/memory-cache/index.mjs
test/__test__/apps/spa.spec.mjs
test/__test__/basic.spec.mjs
test/fixtures/use-cache-concurrency.jsx
test/fixtures/use-cache-invalidate.jsx
test/vitestSetup.mjs

Fixes `useCache` concurrency by introducing locking on the same key.
Adds a test case to test `"use cache"` concurrency where only a single line should be logged when serving concurrent requests.

fix: useCache concurrency

---

packages/react-server/lib/plugins/use-cache-inline.mjs
packages/react-server/memory-cache/index.mjs
packages/react-server/package.json
packages/react-server/server/cache.mjs
pnpm-lock.yaml
test/__test__/basic.spec.mjs
test/fixtures/use-cache-dynamic.jsx
test/vitest.config.mjs

Fixes `"use cache"` when using the directive in a function with params where the param should be included in the cache key.
Changes in-memory cache implementation to use `deep-eql` for deep equality check on the cache key segments.

fix: use cache in a function with params

---

docs/src/components/Sidebar.module.css

On media query screens of `lg` the `Sidebar` scroll breaks due to `min-height: min-content`
**Before**
https://github.com/user-attachments/assets/7fa2b4c4-3b92-464e-b8ad-43855a11c80d
**After**
https://github.com/user-attachments/assets/5f5e13af-c68c-4fa9-ba04-f738850c0134

fix(docs): sidebar scroll container

---

packages/react-server/lib/build/static.mjs

This PR fixes static site generation when the memory cache, the form data parser, or any runtime value defined in the configuration is used during generation.

fix: ssg runtime references

---

docs/src/pages/en/(pages)/framework/error-handling.mdx
docs/src/pages/en/framework.(index).mdx
packages/react-server/server/create-worker.mjs
packages/react-server/server/render-dom.mjs
packages/react-server/server/render-rsc.jsx

There was a race condition in the error handling when the SSR renderer in the worker sent start and error messages back to the main thread. With this PR the error is just saved and sent with the "start" message to mitigate race conditions.
This PR also adds a documentation page about the framework-level error boundary component and how to use it to handle errors granularly.

fix: error handling race condition when using ssr rendering

---

packages/react-server/lib/plugins/react-server-runtime.mjs
packages/react-server/server/render-dom.mjs
packages/react-server/server/render-rsc.jsx
test/__test__/basic.spec.mjs
test/fixtures/client-component.jsx
test/fixtures/suspense-client.jsx

This fixes an issue about adding scripts to the HTML document in development mode for HMR when the initial page don't use a client component, but a client component is rendered in a `<Suspense>` boundary. #77 
Adds a test to verify this use case from now on.

fix: suspense client component

---

packages/react-server/lib/plugins/file-router/plugin.mjs

Adds support for async functions as static parameters input in the file-system based router.
```ts
// [id].static.ts
export default async () => [{ id: 1 }, { id: 2 }, { id: 3 }];
```
#81

fix: support async functions as static parameters input in file-system based router

---

packages/react-server/lib/build/server.mjs

Adds missing `publicDir` configuration to build Vite config to enable custom public directory configuration other than the default `public`. #82

fix: build with custom public dir

---

packages/react-server/client/ClientProvider.jsx
packages/react-server/lib/handlers/error.mjs
packages/react-server/lib/handlers/static.mjs
packages/react-server/lib/start/ssr-handler.mjs
packages/react-server/server/RemoteComponent.jsx
packages/react-server/server/redirects.mjs
packages/react-server/server/render-rsc.jsx
packages/react-server/server/request.mjs

Adds encoding to HTTP headers from the client and also adds `charset=utf-8` to all HTTP `Content-Type` headers to support exotic characters in client component and server function paths and also in outlet names. #84

fix: encode headers and use charset utf-8 on content-type response headers

---

examples/todo/package.json
pnpm-lock.yaml

Upgrade `better-sqlite3` in the Todo example to support Node.js 23.x

fix(examples): upgrade better-sqlite3 in todo example

---

packages/react-server/server/RemoteComponent.jsx

Reverts `RemoteComponent` outlet header encoding as it was a breaking change.

fix: revert remote component outlet encoding

---

docs/react-server.config.mjs
docs/src/pages/en/(pages)/deploy/api.mdx
docs/src/pages/en/(pages)/framework/cli.mdx
docs/src/pages/en/(pages)/router/server-routing.mdx
docs/src/pages/en/(pages)/router/static.page.mdx
packages/react-server-adapter-core/index.mjs
packages/react-server-adapter-vercel/index.mjs
packages/react-server/bin/commands/build.mjs
packages/react-server/client/ClientProvider.jsx
packages/react-server/client/Link.jsx
packages/react-server/client/ReactServerComponent.jsx
packages/react-server/lib/build/static.mjs
packages/react-server/lib/dev/ssr-handler.mjs
packages/react-server/lib/handlers/error.mjs
packages/react-server/lib/handlers/static.mjs
packages/react-server/lib/handlers/trailing-slash.mjs
packages/react-server/lib/start/manifest.mjs
packages/react-server/lib/start/ssr-handler.mjs
packages/react-server/server/RemoteComponent.jsx
packages/react-server/server/Route.jsx
packages/react-server/server/cache.mjs
packages/react-server/server/render-context.mjs
packages/react-server/server/render-rsc.jsx
packages/react-server/server/request.mjs
packages/react-server/server/router.d.ts
packages/react-server/server/symbols.mjs
pnpm-lock.yaml

This PR fixes issues around static generated RSC x-component files and how response type selection works to send an RSC payload. The response type selection needs to be on par with the static generation to maintain the same solution for both static and dynamic rendering.
Changes request payload to select RSC rendering. Instead of using HTTP headers, the framework now uses an URL pathname suffix, including outlet name and remote or standard RSC rendering and static generation uses the same format in filenames. This fixes #95.
Adds build options to enable compression (GZip and Brotli) and opt-out of static RSC rendering, see more about this in the updated docs.
Adds static export option to render a single outlet. This is mainly to keep consistency with the URL format right now, but might be …

fix: static generated RSC x-component and response type selection

---

docs/src/pages/en/(pages)/deploy/api.mdx
packages/react-server-adapter-core/index.d.ts
packages/react-server-adapter-core/index.mjs
packages/react-server/lib/build/adapter.mjs

Fixes handling the `deploy` CLI argument in the build action adapter handler addressing #101.
Adds handling `deploy` property of an adapter implementation when the value of `deploy` is a function. See more in the docs at https://react-server.dev/deploy/api#define-the-adapter-handler. Implements feature request at https://github.com/lazarv/react-server/pull/48#issuecomment-2552492407

fix: handling deploy cli argument in build action adapter handler

---

examples/remote/react-server.config.mjs
examples/remote/react-server.development.config.mjs
examples/remote/react-server.production.config.mjs
packages/react-server/config/index.mjs
packages/react-server/lib/build/static.mjs
packages/react-server/server/render-rsc.jsx

This PR updates and fixes configuration in the `RemoteComponent` example to make it work again in a production build after configuration handling changes introduced by https://github.com/lazarv/react-server/pull/52
As the configuration is now a prebuilt module in production and only includes configuration entries specified in the `react-server.production.config.mjs` file, the import map and shared module resolution information were missing in the production build.
Fixes static export filesize indentation
Fixes remote style link URLs when used in an RSC update request
Fixes remote client component import URL handling

fix: remote example production config

---

packages/react-server/server/render-rsc.jsx

This PR fixes server function response handling when using an RSC response. RSC response was missing the function return value, and now it should always contain both the server function return value and the rendered component when needed.

fix: server function response

---

packages/react-server/lib/dev/create-server.mjs
test/__test__/basic.spec.mjs
test/fixtures/builtin-import.jsx

This PR fixes built-in module import when not using the `node:` protocol for the built-in module, like `import { ... } from "module";` instead of `import { ... } from "node:module";`.

fix: builtin module import

---

docs/src/pages/(root).layout.jsx

Adds missing language (when not using the default language) to canonical URLs

fix(docs): canonical urls missing lang

---

docs/src/pages/ja/guide.(index).mdx

This PR improves the readability of the Japanese guide documentation.
- Revise Japanese expressions in `docs/src/pages/ja/guide.mdx`
- Enhance natural Japanese phrasing
- Standardize technical term translations
Japanese native team members have reviewed and confirmed:
- Natural Japanese language flow
- Appropriate technical terminology
This is a documentation-only change with no impact on functionality.

docs(ja): improve readability of the guide documentation  Guide(index)

---

.github/workflows/release-experimental.yml

Fixes release workflow when not publishing a new version of `@lazarv/react-server`, but need to publish a new version of another package in this repo referencing the latest available experimental version of `@lazarv/react-server`. Fetch the version number from npm.

fix: release experimental workflow

---

docs/src/pages/(root).layout.jsx
docs/src/pages/ja/(pages)/guide/quick-start.mdx

This PR improves the readability of the Japanese guide documentation.
- Revise Japanese expressions in `docs/src/pages/ja/guide/quick-start.mdx`
- Enhance natural Japanese phrasing
- Standardize technical term translations

docs(ja): translate quick-start into Japanese

---

docs/src/pages/ja/integrations.(index).mdx

This Pull Request to add Japanese documentation about integrations/index. This is a documentation-only change with no impact on functionality
https://react-server.dev/ja/integrations
Status
@TKHShun 's review

docs(ja): translate integrations/index into Japanese

---

docs/src/pages/ja/(pages)/integrations/typescript.mdx

This Pull Request to add Japanese documentation about integrations/typescript. This is a documentation-only change with no impact on functionality
https://react-server.dev/integrations/typescript
Status
@TKHShun 's review

docs(ja): translate integrations/typescript into Japanese

---

packages/react-server/bin/commands/build.mjs
packages/react-server/lib/build/server.mjs
packages/react-server/lib/dev/action.mjs
packages/react-server/lib/dev/create-server.mjs
packages/react-server/lib/utils/clear-screen.mjs

Support `--eval` to build a production app:
```sh
npx @lazarv/react-server build -e 'export default function App(){ return <h1>Hello World</h1>; }'
```
Fix `--clear-screen` to properly clear the screen when using the development server.

fix: cli build eval and clear screen

---

docs/src/pages/en/(pages)/framework/cli.mdx

Adds `--eval` to build options
Removes `--dev` from start options
Addresses #156

fix(docs): remove dev from start options, add eval to build options on cli page

---

docs/src/pages/ja/tutorials.(index).mdx

This Pull Request to add Japanese documentation about tutorials(index). This is a documentation-only change with no impact on functionality
https://react-server.dev/tutorials
@TKHShun 's review

docs(ja): translate tutorials(index) into Japanese

---

docs/src/pages/ja/(pages)/guide/server-functions.mdx

This Pull Request to add Japanese guide documentation about guide >> server-function. This is a documentation-only change with no impact on functionality
Status
@AyakaKoyama 's review

docs(ja): translate server-functions guide into japanese

---

docs/src/pages/en/(pages)/integrations/tailwind-css.mdx

update documentation for integrations/tailwind-css
v4: correct typo in import statement
v3: update export syntax in postcss.config.js and tailwind.config.js

docs(en): fix integrations/tailwind-css documentation

---

packages/react-server/lib/dev/create-server.mjs

Reverts Vite CORS config to force disable it, as enabling CORS on the Vite development server was interfering with calling server functions when using a `RemoteComponent`

fix: revert vite cors config

---

docs/src/pages/en/(pages)/router/api.mdx
docs/src/pages/en/(pages)/router/configuration.mdx
docs/src/pages/en/(pages)/router/markdown.mdx
docs/src/pages/en/(pages)/router/middlewares.mdx
docs/src/pages/en/(pages)/router/static.page.mdx

fixed the duplicate order number in the "router" section of the documentation

fix(docs): modify router-docs order number

---

docs/src/pages/ja/(pages)/guide/why.mdx

This commit fixes a typo in the documentation where an extra '?' was present.

fix(docs): fix typo in documentation

---

docs/src/pages/en/(pages)/tutorials/todo-app.mdx

Fixed missing link in TODO tutorial title

fix(docs): add title link in todo tutorials doc

---

packages/react-server/lib/dev/action.mjs
packages/react-server/lib/start/action.mjs

Handle an `unhandledRejection` error, causing both the development and production servers to exit. This PR changes the behavior to log the error but prevents the server from exiting.

fix: handle unhandled rejection

---

examples/todo/src/AddTodo.tsx
packages/react-server/lib/dev/create-server.mjs
packages/react-server/server/action-state.mjs
packages/react-server/server/module-loader.mjs
packages/react-server/server/render-rsc.jsx
packages/react-server/server/symbols.mjs

This PR changes how missing server functions are handled. Instead of redirecting, a missing server function throws an error, which can be captured using a `useActionState` during server-side rendering and can also be captured using an error component or an error boundary to pass control to the developer on how to handle the issue.

fix: handle server function not found

---

docs/src/pages/en/(pages)/tutorials/photos.mdx

Fixed the Tailwind CSS command in the “Using Client Components” tutorial

docs(en): fix setup command in tutorial

---

packages/react-server/package.json
pnpm-lock.yaml

Fix `rolldown-vite` version to 6.3.5 to fix Bun issues

fix: rolldown-vite version rollback

---

packages/react-server/lib/build/client.mjs
packages/react-server/lib/build/server.mjs

Fixes CSS Module scoped names for production builds. This is to prevent client components from having different CSS class names used for SSR/client layers.

fix: css modules scoped name

---

packages/react-server/lib/build/resolve.mjs
packages/react-server/lib/dev/create-logger.mjs

Fixes resolving `react-server-dom-webpack/client.edge` in SSR when using `npm`.
Fixes logger when using a non-string value as the first argument of `console.log`.

fix: ssr resolve react-server-dom-webpack/client.edge
