lazarv/react-server

- .github/workflows/docs.yml
- .github/workflows/issue-close-require.yml
- .github/workflows/issue-labeled.yml
- .github/workflows/lock-closed-issues.yml
- .github/workflows/publish-commit.yml
- .github/workflows/release-experimental.yml
- .github/workflows/semantic-pull-request.yml
Fixes GitHub Action workflows repository conditions
> fix: workflow repository conditions

- packages/react-server/client/entry.client.jsx
Fixes error message display in the Vite error overlay. Error message was truncated before if new-line characters were in the message. Errors like React hydration errors should display properly with the changes applied in this PR.
It also adds a small error indicator in the bottom-left corner of the screen to open the error overlay, as instantly auto-opening the error overlay on page load could be too distracting.
Fixes handling error overlay re-open after closing the overlay using the Escape key.
Related issue is #55
> fix: show full error message in the overlay

- packages/react-server/client/entry.client.jsx
- packages/react-server/lib/dev/action.mjs
Enhances the error overlay display for React hydration errors.
Moves the error indicator into a web component to encapsulate styling.
Fixes development mode watch default.
> feat: hydration error overlay

- README.md
- docs/src/pages/en/(pages)/guide/get-started.mdx
- docs/src/pages/en/(pages)/router/markdown.mdx
- docs/src/pages/en/index.mdx
- docs/src/pages/global.css
Updates documentation "Get Started" page "Next steps" section.
Fixes some code examples in the documentation.
Fixes some styling in the documentation.
Related to #15
> feat: update docs get started page

- docs/src/components/Sidebar.module.css
- docs/src/pages/global.css
This PR adds scrollbar styling for the sidebar, code blocks, and the page.
> feat(docs): scrollbar styling

- docs/src/components/Contributors.jsx
- docs/src/components/NavigationLinks.jsx
- docs/src/components/Sidebar.module.css
- docs/src/components/TableOfContents.jsx
- docs/src/pages/en/(pages)/team/contributors.mdx
Adds a "Contributors" page to the docs using the current contributors provided by the GitHub API
> feat(docs): add contributors page

- docs/src/pages.mjs
- docs/src/pages/@breadcrumb/[[lang]]/[category]/(breadcrumb).[...slug].page.jsx
- docs/src/pages/@contents/[[lang]]/[category]/(table-of-contents).[...slug].page.jsx
- docs/src/pages/@sidebar/[[lang]]/(sidebar).[...slug].page.jsx
- docs/src/pages/en/(404).[[...slug]].page.mdx
Fixes styling and page components on the docs "Not Found" page
> fix(docs): not found page

- examples/pokemon/package.json
- package.json
- packages/react-server/package.json
- pnpm-lock.yaml
- test/package.json
> feat: upgrade vite to 6.1.0

- examples/express/src/app/index.jsx
- examples/express/src/server.mjs
- packages/react-server/lib/build/dependencies.mjs
- packages/react-server/lib/build/resolve.mjs
- packages/react-server/lib/dev/create-server.mjs
- packages/react-server/lib/dev/render-stream.mjs
- packages/react-server/lib/handlers/error.mjs
- packages/react-server/lib/loader/module-alias.mjs
This PR fixes module resolution when using the middleware mode. The changes make the module resolution and error handling in the development server more robust and error tolerant.
Updates the Express example to include a use case accessing the original `request`.
> fix: middleware mode module resolution

- .github/workflows/ci.yml
- packages/create-react-server/package.json
Add missing fields in the package.json of `@lazarv/create-react-server`
> fix: create-react-server package.json

- docs/src/pages/(root).layout.jsx
- docs/src/pages/en/(pages)/team/index.mdx
Fix canonical URLs in the docs.
> fix(docs): canonical urls

- docs/src/pages/@sidebar/[[lang]]/(sidebar).[...slug].page.jsx
Fixes sidebar links in the docs.
> fix(docs): sidebar links

- docs/src/components/NavigationLinks.jsx
Fixes navigation links in the docs.
> fix(docs): navigation links

- docs/src/pages/GET.{sitemap.xml}.server.mjs
Fixes sitemap `<loc>` values in the docs.
> fix(docs): sitemap loc

- packages/react-server/server/render-rsc.jsx
This fixes remote server function calls when using a form action. The app component needs to be rendered when using a remote form action.
> fix: remote server function call

- .github/workflows/docs.yml
- docs/src/mdx-components.jsx
- docs/src/pages/en/guide.(index).mdx
- docs/src/pages/ja/guide.(index).mdx
Use GitHub Actions environment to allow fork PRs to deploy documentation preview to Vercel
Also fixes external Markdown links to open on a new tab
> fix: docs preview workflow

- docs/src/pages/ja/(pages)/guide/get-started.mdx
This Pull Request to add Japanese guide documentation about Get Started. This is a documentation-only change with no impact on functionality
> docs(ja): translate get-started into Japanese

- docs/src/pages/ja/(pages)/integrations/vite.mdx
This Pull Request to add Japanese documentation about integrations/vite. This is a documentation-only change with no impact on functionality
https://react-server.dev/ja/integrations/vite
> docs(ja): translate integrations/vite into Japanese

- docs/src/pages/ja/(pages)/guide/server-components.mdx
> docs(ja): translate server-components into Japanese

- docs/src/pages/ja/(pages)/guide/get-started.mdx
- docs/src/pages/ja/(pages)/guide/why.mdx
This PR fix the links about Japanese documentation.
> docs(ja): update external links in japanese documentation

- docs/messages/ja.json
This Pull Request update category deploy. This is a documentation-only change with no impact on functionality.
> docs(ja): update translation about deploy

- docs/src/pages/ja/(pages)/framework/configuration.mdx
I fixed typo on framework/configuration.
> docs(ja): fixing typo on framework/configuration

- docs/src/pages/ja/(pages)/deploy/adapters.mdx
This Pull Request to add Japanese guide documentation about deploy/adapters. This is a documentation-only change with no impact on functionality
> docs(ja): deploy/Adapters into Japanese

- docs/src/pages/ja/(pages)/framework/cluster.mdx
> docs(ja): translate Cluster Mode into Japanese

- docs/src/pages/ja/(pages)/router/api.mdx
> docs(ja): translate router/api into Japanase

- docs/src/pages/ja/(pages)/router/markdown.mdx
> docs(ja): translate router/markdown into Japanase

- docs/src/pages/en/(pages)/tutorials/todo-app.mdx
fixed tutorials/todo-app setup command(tailwind)
> fix(docs): tutorials/todo-app setup command

- docs/src/pages/ja/(pages)/tutorials/todo-app.mdx
> docs(ja): translate tutorials/todo-app into Japanese

- docs/src/pages/ja/(pages)/team/contributors.mdx
- docs/src/pages/ja/(pages)/team/index.mdx
> fix(docs): ja team index and contributor pages

- docs/src/pages/ja/(pages)/framework/http.mdx
Added Japanese translation for the "HTTP Context" section.
> docs(ja): translate HTTP Context into Japanese

- docs/src/pages/ja/(pages)/framework/middleware-mode.mdx
Translated the "Middleware mode" documentation page into Japanese.
> docs(ja): translate Middleware mode into Japanese

- docs/src/pages/ja/(pages)/deploy/api.mdx
Translated the "Vercel adapter" documentation section into Japanese.
> docs(ja): translate Adapter API into Japanese

- docs/src/pages/ja/(pages)/tutorials/photos.mdx
@TKHShun `s review
doc(en)
https://react-server.dev/tutorials/photos
> docs(ja): translate 'tutorials/photos' to japanese

- docs/src/pages/ja/(pages)/router/error-handling.mdx
@TKHShun `s review
https://react-server.dev/ja/router/error-handling
> docs(ja): translate error-handling doc to ja

- docs/src/components/Link.jsx
Fixing docs link text alignment.
> fix(docs): link text alignment
